---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
      - key: "/prod/fake"
        valueMap:
          env: prod
          service: prod-fake
      - key: "/dev/fake"
        valueMap:
          env: dev
          service: dev-fake