---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 5m
  targetNamespace: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: '0.5.9'
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 1m
  values:
    installCRDs: false